services:
  db:
    image: postgres:16-alpine
    container_name: db_pgsql
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securedb,
      POSTGRES_DB: library
    ports:
      - '5432:5432'

volumes:
  db_data:
    driver: local
