import '@/shared/styles';

import { Toaster } from '@/shared/components/base';

export const metadata = {
  title: 'Welcome to backoffice',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
