export const bookCategories = [
  'Fiction',
  'Non-fiction',
  'Mystery',
  'Fantasy',
  'Science Fiction',
  'Biography',
  'Historical',
  'Self-help',
  'Romance',
  'Thriller',
  'Horror',
  'Childrens',
  'Adventure',
  'Poetry',
  'Graphic Novel',
  'Young Adult',
  'Memoir',
  'Classic',
  'Philosophy',
  'Humor',
];
